// <auto-generated />
using System;
using ExamWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601124013_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamWebApi.Models.Building", b =>
                {
                    b.Property<string>("Adress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TotalFloors")
                        .HasColumnType("int");

                    b.HasKey("Adress");

                    b.HasIndex("TotalFloors");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("ExamWebApi.Models.Elevator", b =>
                {
                    b.Property<Guid>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingAdress")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MaxFloor")
                        .HasColumnType("int");

                    b.Property<int>("MinFloor")
                        .HasColumnType("int");

                    b.Property<string>("ModelID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MoveSpeed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("BuildingAdress");

                    b.HasIndex("ModelID");

                    b.ToTable("Elevators");
                });

            modelBuilder.Entity("ExamWebApi.Models.FloorCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Course")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("CurrentFloor")
                        .HasColumnType("int");

                    b.Property<Guid?>("ElevatorSerialNumber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorSerialNumber");

                    b.HasIndex("Timestamp");

                    b.ToTable("FloorCalls");
                });

            modelBuilder.Entity("ExamWebApi.Models.TripLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DistanceTraveled")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ElevatorSerialNumber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Description");

                    b.HasIndex("ElevatorSerialNumber");

                    b.HasIndex("Timestamp");

                    b.ToTable("TripLogs");
                });

            modelBuilder.Entity("ExamWebApi.Models.Elevator", b =>
                {
                    b.HasOne("ExamWebApi.Models.Building", "Building")
                        .WithMany("Elevators")
                        .HasForeignKey("BuildingAdress")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ExamWebApi.Models.FloorCall", b =>
                {
                    b.HasOne("ExamWebApi.Models.Elevator", "Elevator")
                        .WithMany("FloorCalls")
                        .HasForeignKey("ElevatorSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Elevator");
                });

            modelBuilder.Entity("ExamWebApi.Models.TripLog", b =>
                {
                    b.HasOne("ExamWebApi.Models.Elevator", "Elevator")
                        .WithMany("TripLogs")
                        .HasForeignKey("ElevatorSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Elevator");
                });

            modelBuilder.Entity("ExamWebApi.Models.Building", b =>
                {
                    b.Navigation("Elevators");
                });

            modelBuilder.Entity("ExamWebApi.Models.Elevator", b =>
                {
                    b.Navigation("FloorCalls");

                    b.Navigation("TripLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
